stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Instalando dependencias"
    - npm install
  tags:
    - docker_shell

test:
  stage: test
  script:
    - echo "Ejecutando pruebas"
    - npm test
  tags:
    - docker_shell
