stages:
  - build
  - publish_image

variables:
  IMAGE_NAME: 192.168.0.3:5002/repository/ltepett/python
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  VERSION_DE_MI_APP: 1.0

before_script:
  - echo $CI_JOB_TOKEN
  - echo $IMAGE_NAME
  - echo $VERSION_DE_MI_APP
  - echo $CI_COMMIT_SHORT_SHA
  - echo "Iniciando pipeline y verificando Docker...0"
  #- docker login $NEXUS_HOST -u $NEXUS_USER -p $NEXUS_PASSWORD
  - docker info

build_image:
  stage: build
  tags:
    - docker_shell
  script:
    - echo "Building stage. .."
    #- docker build -t