stages:
  - build
  - publish_image

variables:
  IMAGE_NAME: 172.20.10.5:5002/repository/tcurup-docker/nodejs
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  VERSION_DE_MI_APP: 1.0

before_script:
  - echo $CI_JOB_TOKEN
  - echo $IMAGE_NAME:$IMAGE_TAG
  - echo $VERSION_DE_MI_APP
  - echo $CI_COMMIT_SHORT_SHA
  - echo "Iniciando pipeline y verificando Docker...00"
  - apt-get update && apt-get install -y docker.io  # Instalar Docker en la imagen de Node.js
  - docker login $NEXUS_HOST -u $NEXUS_USER -p $NEXUS_PASSWORD

build_image:
  stage: build
  image: docker:latest  # Cambia a docker:latest para construir la imagen Docker con el Dockerfile
  tags:
    - docker_shell
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

push_image:
  stage: publish_image
  image: docker:latest  # Usa docker:latest para la etapa de push
  tags:
    - docker_shell
  script:
    - echo "Pushing image to Nexus..."
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - echo "Imagen subida correctamente."
