stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the image"
  tags:
    - shell,shared

test:
  stage: test
  script:
    
    - echo "hola mundo test"
  tags:
    - shell,shared

