stages:
  - build
  - publish_image

variables:
  IMAGE_NAME: 172.20.10.5:5002/repository/tcurup-docker/nodejs
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  VERSION_DE_MI_APP: 1.0

before_script:
  - echo $CI_JOB_TOKEN
  - echo $IMAGE_NAME:$IMAGE_TAG
  - echo $VERSION_DE_MI_APP
  - echo $CI_COMMIT_SHORT_SHA
  - echo "Iniciando pipeline y verificando Docker...00"
  - docker login $NEXUS_HOST -u $NEXUS_USER -p $NEXUS_PASSWORD
  # otros comandos


build_image:
  stage: build
  tags:
    - docker_shell
  script:
    - echo "Building stageeee. .."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

push_image:
  stage: publish_image
  tags:
    - docker_shell
  script:
    - echo "Pushing stage..."
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - echo "Pushing stage...2"
   